// https://nuxt.com/docs/api/configuration/nuxt-config
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

function loadSitemapData() {
  try {
    const dataPath = resolve(__dirname, "sitemap-data.json");
    return JSON.parse(readFileSync(dataPath, "utf-8"));
  } catch {
    // Fallback: if sitemap-data.json doesn't exist, return empty
    return [];
  }
}

const sitemapData = loadSitemapData();

export default defineNuxtConfig({
  compatibilityDate: "2025-07-15",
  devtools: { enabled: true },
  modules: ["@nuxtjs/sitemap"],
  site: {
    name: "Chinese Culture Explorer",
    url: "https://chinese-culture.ikber.cc",
  },
  sitemap: {
    // Exclude auto-discovered app pages to avoid duplicate entries.
    // We provide all URLs explicitly via sitemap-data.json (generated by scripts/generate-sitemap-data.mjs).
    excludeAppSources: ["nuxt:pages"],
    urls: sitemapData,
  },
  runtimeConfig: {
    public: {
      baseURL: process.env.NUXT_PUBLIC_BASE_URL || "http://localhost:3000",
      siteUrl: process.env.NUXT_PUBLIC_SITE_URL || "http://localhost:3000",
    },
  },
});
